<!DOCTYPE html>
<html>
<head>
    <style type="text/css">
        body {background-color: #dddddd; color: #5f5f5f; font-size: 12px;}
        form {width: 300px; margin: 50px auto;}
        input {width: 100%;}
    </style>
    <title>Connect to Twitter</title>
</head>
<body>
    <form action="" method="post">
        <label>Phone Number:</label>
        <input type="text" name="phone_number" placeholder="0912xxxxxxx">
        <input type="submit" value="Connect 2 Twitter">
    </form>
</body>
</html>